[snowflake]
user = "Jquan115"
password = "Hacklytics2025"
account = "fyraoxz-flb98787"
warehouse = "COMPUTE_WH"
role = "SYSADMIN"
database = "OFFICE_VISITS_CPT_99213__99214_NEGOTIATED_RATES_NATIONAL_DATASETS"
schema = "SHARED"
